version: '3.5'
services:
  api1: # API - Instância 01
    image: app/rinhabackend_bun
    build:
      context: ./app1
    env_file: .env
    # hostname: api1
    environment:
      HTTP_HOST: "api1"
      HTTP_PORT: 3000
      POOL_SIZE: 50
    container_name: bun_api1
    ports:
      - "3001:3000"
    depends_on:
      - db
    # ports:
    #   - "3000:3000"
    # ports: # pra executar o docker run precisamos passar a porta
      # - "8080:4000" # o `-` no yml significa que é um array
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'
  api2: # API - Instância 01
    image: app/rinhabackend_bun
    env_file: .env
    build:
      context: ./app2
    # hostname: api2
    environment:
      HTTP_HOST: "api2"
      HTTP_PORT: 3000
      POOL_SIZE: 50
    container_name: bun_api2
    ports:
      - "3002:3000"
    depends_on:
      - db
    # ports:
    #   - "3000:3000"
    # ports: # pra executar o docker run precisamos passar a porta
      # - "8080:4000" # o `-` no yml significa que é um array
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'
  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  db: 
    image: redis/redis-stack
    ports:
      - "6379:6379"
    deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: '1.5GB'